---
#   *******************************************
#   Ansible CIS compliance playbook
#   begin     : Tue 10 Apr 2025
#   copyright : (c) 2025 Aricoma team
#   team      : Eduard Vopička, Tomáš Vohralík
#             : Martin Šindelář, Václav Dvorský
#   $Id: compliance.yaml, v0.01 10/04/2025
#   *******************************************

#   --------------------------------------------------------------------
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public Licence as published by
#   the Free Software Foundation; either version 2 of the Licence, or
#   (at your option) any later version.
#   --------------------------------------------------------------------

- name: Check compliance with best practice
  hosts: all
  become: true
  become_user: root
  roles:
    - role: aix
      tags: audit
